name: sanjeev's job 
# trigger point 
on:
  push:
    branches: [ "main1" ]
    paths-ignore:
      - "README.md"
      - "terraform.tfstate"

# creating jobs 
jobs:
  test-job:
    runs-on: ubuntu-latest 
    steps: # what exactly you want to run in ubuntu machine 
#calling first github action to clone my dryrun-aws data to runner machine
      -name: taking code from my repo
        uses: actions/checkout@5
        with:
          ref: main1


    - name: my first step to test github action 
      run: |
        echo "Hello world"
        git version 
        whoami
        ls -a 
       # terraform version
       # docker version
    
    # Configure aws secrets

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v5.1.0
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2


        -name verify aws connection
         run:
          echo "checking with command"
          aws s3 ls
  